#!/bin/bash




<<note

this script will be install any package passed as argument ./install_package.sh <arg>:
note

echo "*******installing $ *********"


sudo apt-get update
sudo apt-get install $ -y


sudo systemctl start $
sudo systemctl enable $


echo"******installed $******"
