#!/bin/bash




<<note

this script will be install any package passed as argument ./install_package.sh <arg>
note

echo "*******installing $1 *********"


sudo apt-get update
sudo apt-get install $1 -y


sudo systemctl start $1
sudo systemctl enable $1
