#!/bin/bash




<<note

this script for install $
note

echo "*******installing $*********"


sudo apt-get update
sudo apt-get install $ -y


sudo systemctl start $
sudo systemctl enable $


echo"******installed $******"
